version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: graphql-auth
    ports:
      - "54321:5432"
